- .editorconfig
- .gitattributes
- .gitignore
- gulpfile.js
- package.json
> init project setup

- .gitignore
- README.md
- bower.json
- gulpfile.js
- index.html
- package.json
> initial commit

- .gitignore
- README.md
- credentials.js.tmpl
- gulpfile.js
- index.html
- src/components/github-api/github-api.js
- src/components/owner-details/owner-details.js
- src/components/repository-list/repository-list.js
- src/credentials.js.tmpl
> refactor API requests and credentials access

- src/components/github-api/github-api.js
- src/components/repository-list/repository-list.js
> show PRs and issues

- config.js
- index.html
- package.json
- src/bootstrap.js
- src/components/footer/footer.css
- src/components/footer/footer.js
- src/components/header/header.css
- src/components/header/header.js
- src/components/owner-details/owner-details.css
- src/components/owner-details/owner-details.js
- src/components/repository-list/repository-list.css
- src/components/repository-list/repository-list.js
> UI enhancements

- config.js
- index.html
- package.json
- src/bootstrap.js
- src/components/footer/footer.js
- src/components/header/header.js
- src/components/owner-details/owner-details.js
- src/components/repository-list/repository-list.js
> change CSS loading to use import

- src/components/repository-list/repository-list.js
> fix React key props console error

- src/bootstrap.js
- src/components/layout/layout.js
> made layout its own component

- src/components/repositories-following/repositories-following.js
- src/components/repositories-personal/repositories-personal.css
- src/components/repositories-personal/repositories-personal.js
- src/components/table-repositories/table-repositories.css
- src/components/table-repositories/table-repositories.js
> create reusable table component for rendering repository lists

- src/components/user-details/user-details.css
- src/components/user-details/user-details.js
> fixed issue with overlapping image by making it responsive

- src/credentials.js.tmpl
> update credentials.js template file

- README.md
- gulpfile.js
- package.json
> setup npm scripts and update README

- src/components/footer/footer.js
- src/components/header/header.js
- src/components/layout/layout.js
- src/components/navigation/navigation.js
- src/components/repositories-following/repositories-following.js
- src/components/repositories-personal/repositories-personal.js
- src/components/user-details/user-details.js
> extend React Component instead of using creatClass

- src/components/repositories-following/repositories-following.js
- src/components/repositories-personal/repositories-personal.js
- src/components/user-details/user-details.js
- src/stores/github/github-store.js
- src/stores/github/github-user.js
> extracted github entities into classes

- src/stores/github/github-issues.js
- src/stores/github/github-repos.js
> Tech debt/issue 41 create store classes

- gulpfile.js
> add fallback path to support HTML5 History / hashHistory

- gulpfile.babel.js
- src/components/repositories-following/repositories-following.tsx
- src/stores/github/github-store.ts
> added catch handling and 404 issue handling

- package.json
- src/components/bootstrap/bootstrap.tsx
- src/components/repositories-following/repositories-following.tsx
- src/components/repositories-personal/repositories-personal.tsx
- src/components/user-details/user-details.tsx
- src/index.tsx
- src/services/github-api.ts
- src/stores/github-store.ts
- webpack.config.common.js
> navigation and routing

- package.json
- src/components/bootstrap/bootstrap.tsx
- src/components/repositories-following/repositories-following.tsx
- src/components/repositories-personal/repositories-personal.tsx
- src/components/table-repositories/table-repositories.tsx
- src/components/user-details/user-details.tsx
- src/index.tsx
- src/services/github-api.ts
- src/stores/github-store.ts
resolves #63 
**TODO**
see linked issues
> getting all repos to load using a more button

- src/services/github-api.ts
> impoved next URL detection logic

- src/components/repositories-following/repositories-following.tsx
- src/components/repositories-personal/repositories-personal.tsx
- src/stores/github-store.ts
> issue state saving improvement WIP

- src/services/github-api.ts
> fixed mis-represented issue counts

- src/components/table-repositories/table-repositories.tsx
> changed index value for tracking in table

- src/services/github-api.spec.js
- src/services/github-api.ts
> fix row highlighting when there are multiple assignees

- README.md
- package.json
- yarn.lock
> README updates

- LICENSE.md
- README.md
- bin/build.sh
- package.json
resolves #118 
TODO
- releases - maybe because only pre-releases are out right now?
- code coverage - because it's in clover, not corbetura?
> adding shields for the project

- src/components/bootstrap/bootstrap.tsx
- src/components/repositories-table/repositories-table.tsx
- src/components/user-details/user-details.tsx
- src/services/github-api.ts
- src/stores/github-store.spec.js
- src/stores/github-store.ts
- src/views/following/following.tsx
- src/views/personal/personal.tsx
> fixing duplicate repos on view re-navigate

- src/components/bootstrap/bootstrap.tsx
- src/components/repositories-table/repositories-table.tsx
- src/index.tsx
- src/views/following/following.tsx
- src/views/personal/personal.tsx
just some general code cleanup
> refactoring state and props between views and repositories table

- README.md
@thescientist13 
As I was going through the setup, felt some clarification could be added. Just my take on the steps. Let me know what you think.
> Format setup steps for readability

- package.json
- src/stores/github-store.spec.js
- src/stores/github-store.ts
- src/views/following/following.tsx
- src/views/personal/personal.tsx
> refactored out hasMoreRepos

- jest.config.json
> added cobertura output

- src/components/bootstrap/bootstrap.spec.jsx
- src/components/bootstrap/bootstrap.tsx
- src/components/footer/footer.css
- src/components/footer/footer.tsx
- src/components/header/header.tsx
- src/components/navigation/navigation.tsx
- src/components/user-details/user-details.tsx
- src/services/github-api.spec.jsx
- src/services/github-api.ts
> Tech debt/issue 119 bootstrap testing

- package.json
- src/components/repositories-table/__snapshots__/repositories-table.spec.jsx.snap
- src/components/repositories-table/repositories-table.spec.jsx
- src/components/repositories-table/repositories-table.tsx
- yarn.lock
resolves #61 also resolves #147
> added filtering by repository name

- src/components/bootstrap/bootstrap.spec.jsx
> Closes #150

- src/services/github-api.ts
> refactored nextReposUrl logic
